### PR TITLE
Copy latest `github.com/devcontainers/features/blob/main/src/common-utils/main.sh`

### PR DESCRIPTION
**Pull request by basnijholt**
I am debugging this container for someone using Windows where in the `postStartCommand` we do a `pip install` of the mounted repo, but get permission errors.

ATM I am just comparing what the various scripts do, and noticed this vendored script received quite a few updates. 

Copied from https://github.com/devcontainers/features/blob/3ea4d6bbd7864bcf7b5a91fdeeb66e4f5a6f46c0/src/common-utils/main.sh

### CODE REVIEW

**Comment by maresb** [comment]
Thanks! I'd propose that we merge this, and then in followup PRs:

1. Also update `features/docker-in-docker/install.sh`
2. Add a GH workflow and Python script to revendor these files automatically

Is there anything further you wanted to add to this?

**Review by maresb — APPROVED** [review]

**Comment by maresb** [comment]
Actually, maybe it'd be simpler to add devcontainers/features as a submodule. Then we wouldn't have to worry about keeping the individual files in sync. (Or if we want to patch something, like removing lsb-release so that we don't have an extra install of Python in the base image, then it's simple to patch a copy.)

**Comment by maresb** [comment]
@basnijholt, this dropped off my radar. Should we merge this?

**Comment by basnijholt** [comment]
TBH I also kind of forgot about it 😅

I recall testing it and it worked, however, I am not 100% sure actually.

**Pull request merged**
